### ISSUE TITLE
Tutorial

### ISSUE THREAD

**Issue by schub91** [ricardojlrufino/webphone-sip#2]
Thanks for your development, but I am new to this, there is the possibility that you can do some tutorial for the installation of this softphone client, in which system it is installed or if it can be installed directly in cPanel and how it is configured, since I have it installed in cpanel and this does not work, could you have to build a server with some special features?

**Comment by ricardojlrufino** [comment]
To use the softphone you must have installed FreeSwitch.
It is recommended to be installed on a stand-alone VPS server.

" could you have to build a server with some special features?"
What features would they be? Would you be willing to pay?
