### ISSUE TITLE
First question: Auto-register

### ISSUE THREAD

**Issue by daniel-lucio** [ricardojlrufino/webphone-sip#4]
I have successfully made your project work, :)
My next question, is it a way to populate and make the webpage to auto-register? Please advise

**Comment by daniel-lucio** [comment]
I am reading in the app/app.js file you have 
$("[data-tab='ConfigPage']").click();
when it is not registered.

So, just confirming, I may include
<prefill with PHP the <input tags>>

$("[data-tab='ConfigPage']").click();
$("[data-localize='save']").click();

This way it will connect and then I can hide the "Congfig" tab with JS. What do you think?

**Comment by ricardojlrufino** [comment]
If it worked, it's a good result ...;)

The best way is you save the data in localStorage using JavaScript

Manually save the first time to see the format of the information
